### ISSUE TITLE
Unwanted validationErrors for null value on nullable type 

### ISSUE THREAD

**Issue by alexstrat** [profusion/apollo-validation-directives#10]
```gql
  type Mutation {
    createBook(book: BookInput): Book!
  }

  input BookInput {
    title: String! @stringLength(max: 5)
    description: String
  }
```

```gql
mutation {
  createBook(book: {
    title: "ddd"
  }) {
    title,
  }
}
```

The `createBook` resolver receives a `validationErrors` on `description` input field: `TypeError: String cannot represent value: undefined` whereas it was not provided.

See this sandbox for [reproduction](https://codesandbox.io/s/unwanted-validation-errors-p4r0m?file=/index.js).

**Comment by cabelitos** [comment]
@alexstrat Ty for the report. I'll take a look in this one
