### ISSUE TITLE
usage with apollo-server-lambda

### ISSUE THREAD

**Issue by PinkaminaDianePie** [profusion/apollo-validation-directives#24]
When i try to use this package with `apollo-server-lambda` i get an error:
`ModuleNotFoundError: Module not found: Error: Can't resolve 'apollo-server' in '.../node_modules/@profusion/apollo-validation-directives/build/lib'`
no idea what is the difference in API between them and if it's even possible to use it with `apollo-server-lambda` (I havesn't seen any working examples so far), but it would be really nice thing

**Comment by cabelitos** [comment]
@PinkaminaDianePie Thank you for the report, I created a PR fixing the issue. https://github.com/profusion/apollo-validation-directives/pull/25

**Comment by PinkaminaDianePie** [comment]
Awesome, thank you! I hope you will have a new release soon with these changes :)

**Comment by cabelitos** [comment]
fixed on 2.0.0 (available on NPM right now)

**Comment by PinkaminaDianePie** [comment]
Thank you, it works now! :) Honestly, that is the first library or example I ever saw, capable to validate inputs with `apollo-server-lambda`. I started to think that it's impossible but you proved me wrong :D

**Comment by cabelitos** [comment]
@PinkaminaDianePie awesome! Yeah, it's possible! We just made a mistake by requiring apollo-server during the execution.
If you have any problems, please let us know!
