### ISSUE TITLE
Usage with appolo-federation

### ISSUE THREAD

**Issue by petrovalex** [profusion/apollo-validation-directives#26]
Could you please give an example how to use it with apollo-federation?

**Comment by cabelitos** [comment]
@petrovalex please look here #27 
I'll try to merge and release a new version ASAP.

**Comment by cabelitos** [comment]
Btw, ty for reporting the issue and using our library

**Comment by cabelitos** [comment]
Please use version 2.0.1 (available on NPM) in order to properly have apollo federation support.

**Comment by petrovalex** [comment]
Thanks a lot!
