### ISSUE TITLE
unwanted `validationError` with nullable field when using @stringLength

### ISSUE THREAD

**Issue by makaivelli** [profusion/apollo-validation-directives#29]
StringLength directive adds `validationError` with `could not convert value to string` message when field is empty on a nullable field.

I saw that you have added a [fix](https://github.com/profusion/apollo-validation-directives/pull/28) (which is not yet released) to a similar issue to other directives, but `@stringLength` also have this problem.

**Comment by barbieri** [comment]
Indeed this applies to all directives

**Comment by cabelitos** [comment]
I`ll take a look

**Comment by cabelitos** [comment]
Fixed. Please use 2.0.2 which is available on NPM right now.
