### ISSUE TITLE
validation adds `field: null` when field is not provided

### ISSUE THREAD

**Issue by makaivelli** [profusion/apollo-validation-directives#30]
It is not possible to use partial update with the validation directives.

The directives add `field: null` even if the input did not contain the (not required) field. This can cause unwanted overwrites on fields.

schema:
```
type Profile {
  name: String @stringLength(max: 120)
  avatarUrl: String @pattern(regexp: ...)
}
```

user input:
```
"name":  "John Doe"
```

the resolver gets after validation:
```
"name": "Jonh Doe",
"avatarUrl": null
```

**Comment by cabelitos** [comment]
I`ll take a look

**Comment by cabelitos** [comment]
Fixed. Please use 2.0.2 which is available on NPM right now.
