### ISSUE TITLE
Validation Field Name not available

### ISSUE THREAD

**Issue by harshitajasth** [profusion/apollo-validation-directives#37]
Hi Y’all,

First of all, thank you for creating the directive helpers! They’ve helped save a lot of time and unnecessary issues!

I have a use case where i would like to see which field is causing validation error, right now we only get the field value or the higher level argument name but not the actual field name. 

This happens with input validation, for read validation I see the field name in the path portion of error string.

Is there any way I can get the field name?

Example:

Type exampleinputType {
Id: string @stringLength(min: 4)
Name: string @stringLength(max: 253)
}

Mutation m {
UpdateExample( exampleInput: {
Id :1 
Name: “example”
}) {}
}
The path error portion shows only updateExample and doesn’t show the actual field(id) which is erroring.

Thanks for the help!

**Comment by barbieri** [comment]
Since #36 this is available inside `extensions`.

**Comment by barbieri** [comment]
could we close this?
