### ISSUE TITLE
Publish on npm as apollo-validation-directives ? 

### ISSUE THREAD

**Issue by alexstrat** [profusion/apollo-validation-directives#7]
Today it's published as `@profusion/apollo-validation-directives` :)

**Comment by barbieri** [comment]
any reason why? We wanted to keep the packages in our org to get some way to share upload permissions and also to get some publicity on our development services ;-)

**Comment by alexstrat** [comment]
Oh ok, sounds legit!

I think scoped packages are usually used to publish a custom version of a package without conflict or regroup packages that are part of a same library / usage (example: `@apollo/*) or for private packages. But don't think there is any rule.

**Comment by cabelitos** [comment]
I'm closing this one for reasons described by @barbieri
